### ISSUE TITLE
auto snapshot

### ISSUE THREAD

**Issue by Ludan678** [sprngr/aseprite-record#11]
why the action delay doesn't work for me, no matter what number I set to it always save every action.

**Comment by Ludan678** [comment]
when I reset the action delay 2 times each to a different number then it works fine

**Comment by sprngr** [comment]
It may be necessary to press the stop button if you had already started it and the action delay has been changed while it was already enabled. Also make sure the name of the sprite you're editing is the one that shows up in the modal meaning that's what it is watching for changes on.

**Comment by sprngr** [comment]
Ok, I think i see what the problem is. If you change the action delay value before starting, it'll be stuck at 1. To make it work now, you need to start the auto capture button and then change the action delay value. I'm going to begin looking into getting a patch together now that I can reproduce this. Sorry for the inconvenience and thank you for raising the issue.
